### ISSUE TITLE
when I refresh the data of recyclerview,app crush;hope to get your help,thanks!!!!!!!!!

### ISSUE THREAD

**Issue by Reteyery** [nikhilpanju/RecyclerViewEnhanced#13]
log belows:
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getHeight()' on a null object reference
                                                                          at com.nikhilpanju.recyclerviewenhanced.RecyclerTouchListener.handleTouchEvent(RecyclerTouchListener.java:474)
                                                                          at com.nikhilpanju.recyclerviewenhanced.RecyclerTouchListener.onInterceptTouchEvent(RecyclerTouchListener.java:127)
                                                                          at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2231)
                                                                          at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2277)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1977)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2066)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2066)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2066)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2066)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2066)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2066)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2485)
                                                                          at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1783)
                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:2835)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2444)
                                                                          at android.view.View.dispatchPointerEvent(View.java:8712)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4236)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4090)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3618)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3684)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3644)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3773)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3652)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3830)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3618)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3684)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3644)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3652)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3618)
                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5962)
                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5936)
                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5896)
                                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6059)
                                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
                                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                          at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                          at android.os.Looper.loop(Looper.java:122)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5400)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by nikhilpanju** [comment]
Line 474 in v1.1 doesn't have a view.getHeight(). In your log, can you post the line which is causing the crash? Also what caused this? notifyDataSetChanged() ? Some more information would be better

**Comment by Reteyery** [comment]
order to develop a function a list to show people's comments he hava received.I use a open souce of recyclerview to refresh new data and load more data which named XRecyclerview (github:com.jcodecraeer:xrecyclerview:1.2.7). maybe be this?

**Comment by Reteyery** [comment]
all code are here:
public class SendCommentFragment extends BaseFragment implements TOYSOnItemChildClicklistener, RecyclerTouchListener.RecyclerTouchListenerHelper,TOYSOnItemClickListener, BaseRvAdapter.IHolderStatus,
        XRecyclerView.LoadingListener,ICommentSendView{
    private View view;
    @Bind(R.id.recycler_view)
    XRecyclerView recyclerView;

    CommentSendAdapter adapter;
    @Inject
    CommentSendPresenter sendPresenter;
    private OnActivityTouchListener touchListener;
    private RecyclerTouchListener onTouchListener;
    private int openOptionsPosition;
    @Override
    public View createView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.activity_msg_layout, null);
        DaggerCommentSendCompotent.builder().commentSendModule(new CommentSendModule(this)).build().inject(this);
        return view;
    }

    @Override
    public void init() {
        adapter = new CommentSendAdapter();
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getContext());
        linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        recyclerView.setLayoutManager(linearLayoutManager);
        recyclerView.setLoadingListener(this);
        adapter.setHolderStausListenter(this);
        adapter.setTOYSOnItemChildClicklistener(this);
        adapter.setTOYSOnItemClickListener(this);
        recyclerView.setAdapter(adapter);

        onTouchListener = new RecyclerTouchListener(getActivity(),recyclerView);
        onTouchListener.setClickable(new RecyclerTouchListener.OnRowClickListener() {
            @Override
            public void onRowClicked(int position) {
                TLog.e(TAG, "onRowClicked position :" + position);
            }

            @Override
            public void onIndependentViewClicked(int independentViewID, int position) {
                TLog.e(TAG, "onIndependentViewClicked position :" + position);
            }
        })
                .setSwipeOptionViews(R.id.report, R.id.delete, R.id.change)
                .setSwipeable(R.id.rowFG, R.id.rowBG, new RecyclerTouchListener.OnSwipeOptionsClickListener() {
                    @Override
                    public void onSwipeOptionClicked(int viewID, int position) {

                        if (viewID == R.id.report) {

                        } else if (viewID == R.id.delete) {
                            try{
                                int commentId = adapter.getDatas().get(position - 1).getComment_id();
                                adapter.getDatas().remove(position - 1);
                                adapter.notifyItemRemoved(position);
                                sendPresenter.requestDeleteComment(commentId);
                            }catch (Exception e){
                                e.printStackTrace();
                            }
                        } else if (viewID == R.id.change) {

                        }

                    }
                });
        recyclerView.addOnItemTouchListener(onTouchListener);
    }

    @Override
    public void operation() {
        sendPresenter.getSendComment(Status.DEFAULT,0,20);
    }

    @Override
    public void onGetSendCommentSuccess(@Status.RefreshStatus int status, DetailCommentModel commentModel) {
        do {
            if(status == Status.DEFAULT) {
                if (commentModel != null && commentModel.getCode() == 200) {
                    adapter.setDatas(commentModel.getData());
                }
                break;
            }
            if(status == Status.DOWN) {
                if (commentModel != null && commentModel.getCode() == 200) {
                    adapter.setDatas(commentModel.getData());
                }
                recyclerView.refreshComplete();
                break;
            }
            if(status == Status.UP) {
                if (commentModel != null && commentModel.getCode() == 200) {
                    adapter.addMoreDatas(commentModel.getData());
                }
                recyclerView.loadMoreComplete();
                break;
            }
        }while(false);
    }

    @Override
    public void onGetSendCommentError(@Status.RefreshStatus int status, Throwable throwable) {
        do {
            if(status == Status.DOWN) {
                recyclerView.refreshComplete();
                break;
            }
            if(status == Status.UP) {
                recyclerView.loadMoreComplete();
                break;
            }
        }while(false);
    }

    @Override
    public void onGetSendCommentFailed(@Status.RefreshStatus int status, ResultResponse response) {
        do {
            if(status == Status.DOWN) {
                recyclerView.refreshComplete();
                break;
            }
            if(status == Status.UP) {
                recyclerView.loadMoreComplete();
                break;
            }
        }while(false);
    }

    @Override
    public void requestDeleteItem(ResultResponse response) {
        if(response != null && response.getCode() == 200){
            new SweetAlertDialog(getActivity(), SweetAlertDialog.SUCCESS_TYPE)
                .setTitleText("温馨提示")
                .setContentText("删除成功！")
                .show();
        }else{
            new SweetAlertDialog(getActivity(), SweetAlertDialog.ERROR_TYPE)
                .setTitleText("温馨提示")
                .setContentText("删除失败！")
                .show();
        }
        adapter.notifyDataSetChanged();
    }

    @Override
    public void holderInitSuccessed(BaseRvAdapter mvhBaseRvAdapter) {
        int[] viewIds = new int[]{R.id.returnBtn, R.id.ll_return,R.id.rl_content,R.id.civ_user_image,R.id.follow};
        adapter.setViewCilckById(viewIds);
    }

    @Override
    public void onRefresh() {
        sendPresenter.getSendComment(Status.DOWN,0,20);
    }

    @Override
    public void onLoadMore() {
        sendPresenter.getSendComment(Status.UP,adapter.getItemCount(),20);
    }

    @Override
    public void onItemChildClick(View v, int position) {
        switch (v.getId()) {
            case R.id.civ_user_image:
                int userId = adapter.getDatas().get(position - 1).getUser_id();
                Intent intent = new Intent(getActivity(), UserInfoActivity.class);
                intent.putExtra(Status.USER_ID, userId);
                startActivity(intent);
                break;
            case R.id.rl_content:
                int objId = adapter.getDatas().get(position - 1).getObject_id();
                int objType = adapter.getDatas().get(position - 1).getObject_type();
                Intent objIntent = new Intent(getActivity(), ArticleDetailActivity.class);
                objIntent.putExtra(Status.DETAIL_ID, objId);
                objIntent.putExtra(Status.DETAIL_TYPE, objType);
                startActivity(objIntent);
        }
    }

    @Override
    public void onRvItemClick(View itemView, int position, BaseRvAdapter mAdapter) {

    }

    @Override
    public void setOnActivityTouchListener(OnActivityTouchListener listener) {

    }
}

Sorry to bother you~thanks

**Comment by Reteyery** [comment]
class RecyclerTouchListener the line 521 bgView.setMinimumHeight(fgView.getHeight());  will it?

**Comment by Reteyery** [comment]
I solved it... thanks all the same
